### ISSUE TITLE
Running latest commit

### ISSUE THREAD

**Issue by sblanchard** [DunnCreativeSS/deribitBitmexMarketMaker_ByFunding#1]
Fresh Deribit account with BTC and ETH balances and no open positions.
And getting following output:

********************************************************************
Start Time:        2020-03-07 03:21:11
Current Time:      2020-03-07 03:21:11
Days:              0.0
Hours:             0.0
Spot Price:        9116.66
Equity ($):          69.43
P&L ($)               0.00
Equity (BTC):       0.0076
P&L (BTC)           0.0000

Positions        Contracts
BTC-25SEP20              0
BTC-26JUN20              0
BTC-27MAR20              0
BTC-PERPETUAL            0

Vols               %
BTC-25SEP20      150
BTC-26JUN20      150
BTC-27MAR20      150
BTC-PERPETUAL    150
btc              150
{'BTC-25SEP20': {'arb': 1.0665638512349918, 'long': 'BTC-PERPETUAL', 'short': 'BTC-25SEP20'}, 'BTC-26JUN20': {'arb': 1.0394157509438764, 'long': 'BTC-PERPETUAL', 'short': 'BTC-26JUN20'}, 'BTC-27MAR20': {'arb': 1.006399273418116, 'long': 'BTC-PERPETUAL', 'short': 'BTC-27MAR20'}}
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
edit error
Failed: invalid_quantity
local variable 'oid' referenced before assignment
RESTARTING .
RESTARTING ..
RESTARTING ...
RESTARTING ....
RESTARTING .....

Halp!

**Comment by DunnCreativeSS** [comment]
Can you try the latest commit? Those edit errors are OK, I removed all the references to OID and now it should run without restarting.

Have you signed up for my deribit ref link? :D 

If you're running BTC and ETH can you do me a favor..

find these lines:

f 'PERPETUAL' in fut:
                pos_lim_short = pos_lim_short * (len(self.futures)  - 1)
                pos_lim_long = pos_lim_long * (len(self.futures) - 1)

change them to:

f 'PERPETUAL' in fut:
                pos_lim_short = pos_lim_short * (len(self.futures)  - 1) / 2
                pos_lim_long = pos_lim_long * (len(self.futures) - 1) / 2

find the two lines that say:

qty = qty * len(self.futures)

change them to:

qty = qty * len(self.futures) / 2

**Comment by DunnCreativeSS** [comment]
Also your invalid quantity error means your pct qty base is too small. Try doubling it then running doubling it then running until Iy starts entering orders at 10 futures and 30 or 40 perp

**Comment by sblanchard** [comment]
Thanks for the ninja edits and hints. I'll open a new account with with your referral link soon, your project reminded me I had a new one with a few pennies in it. Let's see how it fares.

**Comment by DunnCreativeSS** [comment]
Great! Good luck. Returns aren't assured or implied and risk only what you can afford to lose..  otherwise have fun!

**Comment by DunnCreativeSS** [comment]
@sblanchard did the bot end up working? did you end up signing up via ref link :)?
